/**
	anotherSubMachine1.c

	This file automatically generated by FSMLang
*/

#include "anotherSubMachine1_priv.h"
#include <stddef.h>

#ifndef DBG_PRINTF
#define DBG_PRINTF(...)
#endif

/* FSMLANG_DEVELOP: declare_sub_machine_if */
extern ANOTHER_SUB_MACHINE1_SUB_FSM_IF anotherSubMachine1_anotherSubSubMachine1_sub_fsm_if;

static ANOTHER_NEW_MACHINE_EVENT ss1_stateFn(pANOTHER_SUB_MACHINE1,ANOTHER_NEW_MACHINE_EVENT);
static ANOTHER_NEW_MACHINE_EVENT ss2_stateFn(pANOTHER_SUB_MACHINE1,ANOTHER_NEW_MACHINE_EVENT);
static ANOTHER_NEW_MACHINE_EVENT ss3_stateFn(pANOTHER_SUB_MACHINE1,ANOTHER_NEW_MACHINE_EVENT);

static const ANOTHER_SUB_MACHINE1_STATE_FN anotherSubMachine1_state_fn_array[anotherSubMachine1_numStates] = 
{
	  ss1_stateFn
	, ss2_stateFn
	, ss3_stateFn
};

/* FSMLANG_DEVELOP: defineSubMachineIF */
ANOTHER_NEW_MACHINE_EVENT anotherNewMachine_anotherSubMachine1_sub_machine_fn(ANOTHER_NEW_MACHINE_EVENT e)
{
	return anotherSubMachine1FSM(panotherSubMachine1,e);
}

ANOTHER_NEW_MACHINE_SUB_FSM_IF anotherNewMachine_anotherSubMachine1_sub_fsm_if =
{
		.subFSM = anotherNewMachine_anotherSubMachine1_sub_machine_fn
	, .first_event = anotherNewMachine_anotherSubMachine1_ee1
	, .last_event = anotherNewMachine_anotherSubMachine1_e1
};

/* FSMLANG_DEVELOP: define_needed_shared_event_structures */
/* FSMLANG_DEVELOP: define_needed_shared_event_structures */
/* FSMLANG_DEVELOP: define_needed_shared_event_structures */
/* FSMLANG_DEVELOP: define_needed_shared_event_structures */
/* FSMLANG_DEVELOP: print_shared_event_data_block_signature */
ANOTHER_NEW_MACHINE_SHARED_EVENT_STR anotherSubMachine1_share_anotherNewMachine_e1_str = {
	  .event               = THIS(e1)
	, .psub_fsm_if         = &anotherNewMachine_anotherSubMachine1_sub_fsm_if
};

/* FSMLANG_DEVELOP: defineSubMachineArray */

pANOTHER_SUB_MACHINE1_SUB_FSM_IF const anotherSubMachine1_sub_fsm_if_array[THIS(numSubMachines)] =
{
/* FSMLANG_DEVELOP: print_sub_machine_if */
	&anotherSubMachine1_anotherSubSubMachine1_sub_fsm_if
};

/* FSMLANG_DEVELOP: define_parent_event_reference_elements */
/* FSMLANG_DEVELOP: define_shared_event_lists */
pANOTHER_SUB_MACHINE1_SHARED_EVENT_STR sharing_anotherSubMachine1_ee1[] =
{
/* FSMLANG_DEVELOP: reference_shared_event_data_blocks */
	  &/* FSMLANG_DEVELOP: print_shared_event_data_block_signature */
anotherSubSubMachine1_share_anotherSubMachine1_ee1_str
	, NULL
};

/* FSMLANG_DEVELOP: define_shared_event_lists */
/* FSMLANG_DEVELOP: define_shared_event_lists */
/* FSMLANG_DEVELOP: define_shared_event_lists */
pANOTHER_SUB_MACHINE1_SHARED_EVENT_STR sharing_anotherSubMachine1_e1[] =
{
/* FSMLANG_DEVELOP: reference_shared_event_data_blocks */
	  &/* FSMLANG_DEVELOP: print_shared_event_data_block_signature */
anotherSubSubMachine1_share_anotherSubMachine1_e1_str
	, NULL
};

ANOTHER_NEW_MACHINE_EVENT anotherSubMachine1_pass_shared_event(pANOTHER_SUB_MACHINE1_SHARED_EVENT_STR sharer_list[])
{
	ANOTHER_NEW_MACHINE_EVENT return_event = THIS(noEvent);
	for (pANOTHER_SUB_MACHINE1_SHARED_EVENT_STR *pcurrent_sharer = sharer_list;
	     *pcurrent_sharer && return_event == THIS(noEvent);
	     pcurrent_sharer++)
	{
		return_event = (*(*pcurrent_sharer)->psub_fsm_if->subFSM)((*pcurrent_sharer)->event);
	}

	return return_event;
}

/* FSMLANG_DEVELOP: generateInstance */
ANOTHER_SUB_MACHINE1 anotherSubMachine1 = {
	anotherSubMachine1_ss1,
	THIS(ee1),
	&anotherSubMachine1_state_fn_array,
	&anotherSubMachine1_sub_fsm_if_array,
	anotherSubMachine1FSM
};

pANOTHER_SUB_MACHINE1 panotherSubMachine1 = &anotherSubMachine1;

/* FSMLANG_DEVELOP: defineCSwitchSubMachineFSM */

#ifndef EVENT_IS_NOT_EXCLUDED_FROM_LOG
#define EVENT_IS_NOT_EXCLUDED_FROM_LOG(e) (e == e)
#endif
ANOTHER_NEW_MACHINE_EVENT anotherSubMachine1FSM(pANOTHER_SUB_MACHINE1 pfsm, ANOTHER_NEW_MACHINE_EVENT event)
{
	ANOTHER_NEW_MACHINE_EVENT e = event;

	while (
		(e != THIS(noEvent))
		&& (e >= THIS(ee1))
	)
	{

#ifdef ANOTHER_SUB_MACHINE1_DEBUG
if (EVENT_IS_NOT_EXCLUDED_FROM_LOG(e))
{
	DBG_PRINTF("event: %s; state: %s"
,ANOTHER_SUB_MACHINE1_EVENT_NAMES[e - THIS(ee1)]
,ANOTHER_SUB_MACHINE1_STATE_NAMES[pfsm->state]
);
}
#endif

	/* This is read-only data to facilitate error reporting in action functions */
	pfsm->event = e;

		e = ((* (*pfsm->statesArray)[pfsm->state])(pfsm,e));

	}

	return e == THIS(noEvent) ? PARENT(noEvent) : e;
}

/* FSMLANG_DEVELOP: defineStateEntryAndExitManagers */
static ANOTHER_NEW_MACHINE_EVENT ss1_stateFn(pANOTHER_SUB_MACHINE1 pfsm,ANOTHER_NEW_MACHINE_EVENT e)
{
	ANOTHER_NEW_MACHINE_EVENT retVal = THIS(noEvent);

	switch(e)
	{
	case THIS(ee1):
		retVal = anotherNewMachine_anotherSubMachine1_aa1(pfsm);
		pfsm->state = anotherSubMachine1_ss2;
		break;
	case THIS(ee2):
		retVal = anotherNewMachine_anotherSubMachine1_aa2(pfsm);
		pfsm->state = anotherSubMachine1_ss3;
		break;
	default:
		DBG_PRINTF("anotherNewMachine_anotherSubMachine1_noAction");
		break;
	}

	return retVal;
}

static ANOTHER_NEW_MACHINE_EVENT ss2_stateFn(pANOTHER_SUB_MACHINE1 pfsm,ANOTHER_NEW_MACHINE_EVENT e)
{
	ANOTHER_NEW_MACHINE_EVENT retVal = THIS(noEvent);

	switch(e)
	{
	default:
		DBG_PRINTF("anotherNewMachine_anotherSubMachine1_noAction");
		break;
	}

	/* we only just now know we did not use this */
	(void) pfsm;

	return retVal;
}

static ANOTHER_NEW_MACHINE_EVENT ss3_stateFn(pANOTHER_SUB_MACHINE1 pfsm,ANOTHER_NEW_MACHINE_EVENT e)
{
	ANOTHER_NEW_MACHINE_EVENT retVal = THIS(noEvent);

	switch(e)
	{
	default:
		DBG_PRINTF("anotherNewMachine_anotherSubMachine1_noAction");
		break;
	}

	/* we only just now know we did not use this */
	(void) pfsm;

	return retVal;
}


/* FSMLANG_DEVELOP: define_weak_action_function */
ANOTHER_NEW_MACHINE_EVENT __attribute__((weak)) THIS(aa1)(FSM_TYPE_PTR pfsm)
{
	DBG_PRINTF("weak: %s", __func__);
	(void) pfsm;
	return anotherSubMachine1_pass_shared_event(sharing_anotherSubMachine1_ee1);
}

/* FSMLANG_DEVELOP: define_weak_action_function */
ANOTHER_NEW_MACHINE_EVENT __attribute__((weak)) THIS(aa2)(FSM_TYPE_PTR pfsm)
{
	DBG_PRINTF("weak: %s", __func__);
	(void) pfsm;
	return THIS(noEvent);
}


#ifdef ANOTHER_SUB_MACHINE1_DEBUG
char *ANOTHER_SUB_MACHINE1_EVENT_NAMES[] = {
	 "anotherNewMachine_anotherSubMachine1_ee1"
	,"anotherNewMachine_anotherSubMachine1_ee2"
	,"anotherNewMachine_anotherSubMachine1_ee3"
	,"anotherNewMachine_anotherSubMachine1_e1"
	, "anotherSubMachine1_noEvent"
	, "anotherSubMachine1_numEvents"
	, "anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_y1"
	, "anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_y2"
	, "anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_e1"
	, "anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_ee1"
	, "anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_noEvent"
};

char *ANOTHER_SUB_MACHINE1_STATE_NAMES[anotherSubMachine1_numStates] = {
	 "anotherNewMachine_anotherSubMachine1_ss1"
	,"anotherNewMachine_anotherSubMachine1_ss2"
	,"anotherNewMachine_anotherSubMachine1_ss3"
};

#endif
