/**
	anotherSubSubMachine1.c

	This file automatically generated by FSMLang
*/

#include "anotherSubSubMachine1_priv.h"
#include <stddef.h>

#ifndef DBG_PRINTF
#define DBG_PRINTF(...)
#endif

static ANOTHER_NEW_MACHINE_EVENT z1_stateFn(pANOTHER_SUB_SUB_MACHINE1,ANOTHER_NEW_MACHINE_EVENT);
static ANOTHER_NEW_MACHINE_EVENT z2_stateFn(pANOTHER_SUB_SUB_MACHINE1,ANOTHER_NEW_MACHINE_EVENT);

static const ANOTHER_SUB_SUB_MACHINE1_STATE_FN anotherSubSubMachine1_state_fn_array[anotherSubSubMachine1_numStates] = 
{
	  z1_stateFn
	, z2_stateFn
};

/* FSMLANG_DEVELOP: defineSubMachineIF */
ANOTHER_NEW_MACHINE_EVENT anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_sub_machine_fn(ANOTHER_NEW_MACHINE_EVENT e)
{
	return anotherSubSubMachine1FSM(panotherSubSubMachine1,e);
}

ANOTHER_SUB_MACHINE1_SUB_FSM_IF anotherSubMachine1_anotherSubSubMachine1_sub_fsm_if =
{
		.subFSM = anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_sub_machine_fn
	, .first_event = anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_y1
	, .last_event = anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_ee1
};

/* FSMLANG_DEVELOP: define_needed_shared_event_structures */
/* FSMLANG_DEVELOP: define_needed_shared_event_structures */
/* FSMLANG_DEVELOP: define_needed_shared_event_structures */
/* FSMLANG_DEVELOP: print_shared_event_data_block_signature */
ANOTHER_SUB_MACHINE1_SHARED_EVENT_STR anotherSubSubMachine1_share_anotherSubMachine1_e1_str = {
	  .event               = THIS(e1)
	, .psub_fsm_if         = &anotherSubMachine1_anotherSubSubMachine1_sub_fsm_if
};

/* FSMLANG_DEVELOP: define_needed_shared_event_structures */
/* FSMLANG_DEVELOP: print_shared_event_data_block_signature */
ANOTHER_SUB_MACHINE1_SHARED_EVENT_STR anotherSubSubMachine1_share_anotherSubMachine1_ee1_str = {
	  .event               = THIS(ee1)
	, .psub_fsm_if         = &anotherSubMachine1_anotherSubSubMachine1_sub_fsm_if
};

/* FSMLANG_DEVELOP: defineSubMachineArray */
/* FSMLANG_DEVELOP: generateInstance */
ANOTHER_SUB_SUB_MACHINE1 anotherSubSubMachine1 = {
	anotherSubSubMachine1_z1,
	THIS(y1),
	&anotherSubSubMachine1_state_fn_array,
	anotherSubSubMachine1FSM
};

pANOTHER_SUB_SUB_MACHINE1 panotherSubSubMachine1 = &anotherSubSubMachine1;

/* FSMLANG_DEVELOP: defineCSwitchSubMachineFSM */

#ifndef EVENT_IS_NOT_EXCLUDED_FROM_LOG
#define EVENT_IS_NOT_EXCLUDED_FROM_LOG(e) (e == e)
#endif
ANOTHER_NEW_MACHINE_EVENT anotherSubSubMachine1FSM(pANOTHER_SUB_SUB_MACHINE1 pfsm, ANOTHER_NEW_MACHINE_EVENT event)
{
	ANOTHER_NEW_MACHINE_EVENT e = event;

	while (
		(e != THIS(noEvent))
		&& (e >= THIS(y1))
	)
	{

#ifdef ANOTHER_SUB_SUB_MACHINE1_DEBUG
if (EVENT_IS_NOT_EXCLUDED_FROM_LOG(e))
{
	DBG_PRINTF("event: %s; state: %s"
,ANOTHER_SUB_SUB_MACHINE1_EVENT_NAMES[e - THIS(y1)]
,ANOTHER_SUB_SUB_MACHINE1_STATE_NAMES[pfsm->state]
);
}
#endif

	/* This is read-only data to facilitate error reporting in action functions */
	pfsm->event = e;

		e = ((* (*pfsm->statesArray)[pfsm->state])(pfsm,e));

	}

	return e == THIS(noEvent) ? PARENT(noEvent) : e;
}

/* FSMLANG_DEVELOP: defineStateEntryAndExitManagers */
static ANOTHER_NEW_MACHINE_EVENT z1_stateFn(pANOTHER_SUB_SUB_MACHINE1 pfsm,ANOTHER_NEW_MACHINE_EVENT e)
{
	ANOTHER_NEW_MACHINE_EVENT retVal = THIS(noEvent);

	switch(e)
	{
	case THIS(y1):
		retVal = anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_x1(pfsm);
		break;
	case THIS(y2):
		retVal = anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_x2(pfsm);
		pfsm->state = anotherSubSubMachine1_z2;
		break;
	default:
		DBG_PRINTF("anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_noAction");
		break;
	}

	return retVal;
}

static ANOTHER_NEW_MACHINE_EVENT z2_stateFn(pANOTHER_SUB_SUB_MACHINE1 pfsm,ANOTHER_NEW_MACHINE_EVENT e)
{
	ANOTHER_NEW_MACHINE_EVENT retVal = THIS(noEvent);

	switch(e)
	{
	default:
		DBG_PRINTF("anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_noAction");
		break;
	}

	/* we only just now know we did not use this */
	(void) pfsm;

	return retVal;
}


/* FSMLANG_DEVELOP: define_weak_action_function */
ANOTHER_NEW_MACHINE_EVENT __attribute__((weak)) THIS(x1)(FSM_TYPE_PTR pfsm)
{
	DBG_PRINTF("weak: %s", __func__);
	(void) pfsm;
	return THIS(noEvent);
}

/* FSMLANG_DEVELOP: define_weak_action_function */
ANOTHER_NEW_MACHINE_EVENT __attribute__((weak)) THIS(x2)(FSM_TYPE_PTR pfsm)
{
	DBG_PRINTF("weak: %s", __func__);
	(void) pfsm;
	return THIS(noEvent);
}


#ifdef ANOTHER_SUB_SUB_MACHINE1_DEBUG
char *ANOTHER_SUB_SUB_MACHINE1_EVENT_NAMES[] = {
	 "anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_y1"
	,"anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_y2"
	,"anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_e1"
	,"anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_ee1"
	, "anotherSubSubMachine1_noEvent"
	, "anotherSubSubMachine1_numEvents"
};

char *ANOTHER_SUB_SUB_MACHINE1_STATE_NAMES[anotherSubSubMachine1_numStates] = {
	 "anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_z1"
	,"anotherNewMachine_anotherSubMachine1_anotherSubSubMachine1_z2"
};

#endif
