"""
	matter.py

	This file generated by FSMLang

"""

from transitions import Machine

class Matter(object):

	states = [  {'name': 'solid', 'on_enter': ['become_solid'], 'on_exit': ['become_not_solid']}
	            , {'name': 'liquid', 'on_enter': ['become_liquid'], 'on_exit': ['become_not_liquid']}
	            , {'name': 'gas', 'on_enter': ['become_gaseous'], 'on_exit': ['become_not_gaseous']}
	          ]
	transitions = [
	               ['melt', 'solid', 'liquid']
	               , ['evaporate', 'liquid', 'gas']
	               , ['freeze', 'liquid', 'solid']
	               , ['condense', 'gas', 'liquid']
	               ]

	def __init__(self):
		self.machine = Machine(model=self, states=Matter.states, transitions=Matter.transitions, initial='solid')


	def become_solid(self):
		print('become_solid')


	def become_not_solid(self):
		print('become_not_solid')


	def become_liquid(self):
		print('become_liquid')


	def become_not_liquid(self):
		print('become_not_liquid')


	def become_gaseous(self):
		print('become_gaseous')


	def become_not_gaseous(self):
		print('become_not_gaseous')


