override CFLAGS+=-DLEX_DEBUG

#here, it is only necessary to list source files that are not local to the current directory.
SRC=fsm_c_utils.c   \
		fsm_utils.c   \
		list.c        \
		lexer_debug.c \
		ancestry.c

TARGET=diff_canonical

include ../unitTest.mk

