/**
	subMachine2_priv.h

	This file automatically generated by FSMLang
*/

#ifndef _SUBMACHINE2_PRIV_H_
#define _SUBMACHINE2_PRIV_H_

#include "top_level_submach.h"
#include "top_level.h"

#ifdef NEW_MACHINE_SUB_MACHINE2_DEBUG
#include <stdio.h>
#include <stdlib.h>
#endif

/*
	sub-machine events are included in the top-level machine event enumeration.
	These macros set the appropriate names for events from THIS machine
	and those from the PARENT machine.

	They may be turned off as needed.
*/
#ifndef NO_CONVENIENCE_MACROS
#undef UFMN
#define UFMN(A) newMachine_subMachine2_##A
#undef THIS
#define THIS(A) newMachine_subMachine2_##A
#undef STATE
#define STATE(A) subMachine2_##A
#undef ACTION_RETURN_TYPE
#define ACTION_RETURN_TYPE NEW_MACHINE_EVENT_ENUM
#undef FSM_TYPE_PTR
#define FSM_TYPE_PTR pSUB_MACHINE2
#undef DECLARE_INSTANCE
#define DECLARE_INSTANCE(A) FSM_TYPE_PTR A = (FSM_TYPE_PTR) pfsm
#undef DECLARE_TR_FN_RET_VAR
#define DECLARE_TR_FN_RET_VAR(A, B) SUB_MACHINE2_STATE A = STATE(B)
#undef RETURN_STATE
#define RETURN_STATE(A, B) A = STATE(B)
#undef TR_FN_RETURN_TYPE
#define TR_FN_RETURN_TYPE SUB_MACHINE2_STATE
#undef PARENT
#define PARENT(A) newMachine_##A
#endif

#ifdef NEW_MACHINE_SUB_MACHINE2_DEBUG
extern char *SUB_MACHINE2_EVENT_NAMES[];
extern char *SUB_MACHINE2_STATE_NAMES[];
#endif

typedef enum {
	subMachine2_sss1
	, subMachine2_sss2
	, subMachine2_sss3
	, subMachine2_numStates
}  SUB_MACHINE2_STATE;

typedef struct _subMachine2_struct_ SUB_MACHINE2, *pSUB_MACHINE2;
extern pSUB_MACHINE2 psubMachine2;

typedef NEW_MACHINE_EVENT_ENUM (*SUB_MACHINE2_ACTION_FN)(pSUB_MACHINE2);

typedef NEW_MACHINE_EVENT_ENUM (*SUB_MACHINE2_FSM)(pSUB_MACHINE2,NEW_MACHINE_EVENT_ENUM);

typedef enum { newMachine_subMachine2_numEvents = 3} NEW_MACHINE_SUB_MACHINE2_EVENTS;
typedef struct _newMachine_subMachine2_action_trans_struct_ {
	SUB_MACHINE2_ACTION_FN	action;
	SUB_MACHINE2_STATE	transition;
} SUB_MACHINE2_ACTION_TRANS, *pSUB_MACHINE2_ACTION_TRANS;

struct _subMachine2_struct_ {
	unsigned                    instance;
	SUB_MACHINE2_STATE          state;
	NEW_MACHINE_EVENT_ENUM      event;
	SUB_MACHINE2_ACTION_TRANS   const	(*actionArray)[newMachine_subMachine2_numEvents][subMachine2_numStates];
	SUB_MACHINE2_FSM           fsm;
};

NEW_MACHINE_EVENT_ENUM newMachine_subMachine2_aaa1(pSUB_MACHINE2);
NEW_MACHINE_EVENT_ENUM newMachine_subMachine2_aaa2(pSUB_MACHINE2);
NEW_MACHINE_EVENT_ENUM newMachine_subMachine2_noAction(pSUB_MACHINE2);




#endif
