/**
	subMachine1.c

	This file automatically generated by FSMLang
*/

#include "subMachine1_priv.h"
#include <stddef.h>


#ifndef DBG_PRINTF
#define DBG_PRINTF(...)
#endif

static NEW_MACHINE_EVENT_ENUM subMachine1FSM(pSUB_MACHINE1,NEW_MACHINE_EVENT_ENUM);

static void * const subMachine1_INSTANCES[newMachine_numInstances];
static void runAppropriateEntryFunction(SUB_MACHINE1_STATE);
static void runAppropriateExitFunction(SUB_MACHINE1_STATE);
static const SUB_MACHINE1_ACTION_TRANS subMachine1_action_array[THIS(numEvents)][subMachine1_numStates] =
{
	{
		/* -- ee1 -- */

		/* -- ss1 -- */	{UFMN(aa1),subMachine1_ss2}
		/* -- ss2 -- */	, {UFMN(noAction), subMachine1_ss2}
		/* -- ss3 -- */	, {UFMN(noAction), subMachine1_ss3}
		/* -- ss4 -- */	, {UFMN(noAction), subMachine1_ss4}
	},
	{
		/* -- ee2 -- */

		/* -- ss1 -- */	{UFMN(aa2),subMachine1_ss3}
		/* -- ss2 -- */	, {UFMN(noAction), subMachine1_ss2}
		/* -- ss3 -- */	, {UFMN(noAction), subMachine1_ss3}
		/* -- ss4 -- */	, {UFMN(noAction), subMachine1_ss4}
	},
	{
		/* -- ee3 -- */

		/* -- ss1 -- */	{UFMN(noAction), subMachine1_ss1}
		/* -- ss2 -- */	, {UFMN(noAction), subMachine1_ss2}
		/* -- ss3 -- */	, {UFMN(noAction), subMachine1_ss3}
		/* -- ss4 -- */	, {UFMN(noAction), subMachine1_ss4}
	},
};

NEW_MACHINE_EVENT_ENUM THIS(sub_machine_fn)(const void *pfsm, NEW_MACHINE_EVENT_ENUM e)
{
	return ((FSM_TYPE_PTR)pfsm)->fsm((FSM_TYPE_PTR)pfsm,e);
}

NEW_MACHINE_SUB_FSM_IF newMachine_subMachine1_sub_fsm_if =
{
	  .subFSM = THIS(sub_machine_fn)
	, .instanceArray = &subMachine1_INSTANCES
	, .first_event = THIS(firstEvent)
	, .last_event = THIS(noEvent)
};

static SUB_MACHINE1 subMachine1_INSTANCE0 = {
	.state = subMachine1_ss1
	, .event = THIS(ee1)
	, .actionArray = &subMachine1_action_array
	, .instance = 0
	, .fsm = subMachine1FSM
	};
static void * const subMachine1_INSTANCES[newMachine_numInstances] = {
	  &subMachine1_INSTANCE0
};
static void runAppropriateEntryFunction(SUB_MACHINE1_STATE);
static void runAppropriateExitFunction(SUB_MACHINE1_STATE);
#ifndef EVENT_IS_NOT_EXCLUDED_FROM_LOG
#define EVENT_IS_NOT_EXCLUDED_FROM_LOG(e) (e == e)
#endif
static NEW_MACHINE_EVENT_ENUM subMachine1FSM(pSUB_MACHINE1 pfsm, NEW_MACHINE_EVENT_ENUM event)
{
	NEW_MACHINE_EVENT_ENUM new_e;
	NEW_MACHINE_EVENT_ENUM e = event;
	SUB_MACHINE1_STATE new_s;
	while (
		(e != THIS(noEvent))
		&& (e >= THIS(ee1))
	)
	{

#ifdef NEW_MACHINE_SUB_MACHINE1_DEBUG
if ((EVENT_IS_NOT_EXCLUDED_FROM_LOG(e))
    && (e >= THIS(firstEvent))
    && (e < THIS(noEvent))
   )
{
	DBG_PRINTF("event: %s; state: %s"
,SUB_MACHINE1_EVENT_NAMES[e - THIS(firstEvent)]
,SUB_MACHINE1_STATE_NAMES[pfsm->state]
);
}
#endif

	/* This is read-only data to facilitate error reporting in action functions */
	pfsm->event = e;

		new_e = ((* (*pfsm->actionArray)[e - THIS(ee1)][pfsm->state].action)(pfsm));

		new_s = (*pfsm->actionArray)[e - THIS(ee1)][pfsm->state].transition;


		if (pfsm->state != new_s)
		{
		runAppropriateExitFunction(pfsm->state);
		runAppropriateEntryFunction(new_s);
			pfsm->state = new_s;

		}

		e = new_e;


	}

	return e == THIS(noEvent) ? PARENT(noEvent) : e;

}

static void runAppropriateEntryFunction(SUB_MACHINE1_STATE s)
{
	switch(s)
	{
	case subMachine1_ss1:
		newMachine_subMachine1_foo();
		break;
	case subMachine1_ss2:
		newMachine_subMachine1_onEntryTo_ss2();
		break;
	case subMachine1_ss3:
		newMachine_subMachine1_foo1();
		break;
	default:
		break;
	}
}

static void runAppropriateExitFunction(SUB_MACHINE1_STATE s)
{
	switch(s)
	{
	case subMachine1_ss1:
		newMachine_subMachine1_bar();
		break;
	case subMachine1_ss2:
		newMachine_subMachine1_onExitFrom_ss2();
		break;
	case subMachine1_ss4:
		newMachine_subMachine1_bar1();
		break;
	default:
		break;
	}
}

ACTION_RETURN_TYPE __attribute__((weak)) UFMN(aa1)(FSM_TYPE_PTR pfsm)
{
	DBG_PRINTF("weak: %s", __func__);
	(void) pfsm;
	return THIS(noEvent);
}

ACTION_RETURN_TYPE __attribute__((weak)) UFMN(aa2)(FSM_TYPE_PTR pfsm)
{
	DBG_PRINTF("weak: %s", __func__);
	(void) pfsm;
	return THIS(noEvent);
}

ACTION_RETURN_TYPE __attribute__((weak)) UFMN(noAction)(FSM_TYPE_PTR pfsm)
{
	DBG_PRINTF("weak: %s", __func__);
	(void) pfsm;
	return THIS(noEvent);
}

void __attribute__((weak)) newMachine_subMachine1_ee1_dt(pNEW_MACHINE_DATA pdata, const void * pfsm)
{
	(void) pdata;
	(void) pfsm;

	DBG_PRINTF("weak: %s", __func__);
}

	(void) pdata;
	(void) pfsm;

	DBG_PRINTF("weak: %s", __func__);
}

void __attribute__((weak)) newMachine_subMachine1_foo(void)
{
	DBG_PRINTF("weak: %s", __func__);
}

void __attribute__((weak)) newMachine_subMachine1_bar(void)
{
	DBG_PRINTF("weak: %s", __func__);
}

void __attribute__((weak)) newMachine_subMachine1_onEntryTo_ss2(void)
{
	DBG_PRINTF("weak: %s", __func__);
}

void __attribute__((weak)) newMachine_subMachine1_onExitFrom_ss2(void)
{
	DBG_PRINTF("weak: %s", __func__);
}

void __attribute__((weak)) newMachine_subMachine1_foo1(void)
{
	DBG_PRINTF("weak: %s", __func__);
}

void __attribute__((weak)) newMachine_subMachine1_bar1(void)
{
	DBG_PRINTF("weak: %s", __func__);
}


#ifdef NEW_MACHINE_SUB_MACHINE1_DEBUG
char *SUB_MACHINE1_EVENT_NAMES[] = {
	 "newMachine_subMachine1_ee1"
	,"newMachine_subMachine1_ee2"
	,"newMachine_subMachine1_ee3"
	, "subMachine1_noEvent"
	, "subMachine1_numEvents"
};

char *SUB_MACHINE1_STATE_NAMES[] = {
	 "newMachine_subMachine1_ss1"
	,"newMachine_subMachine1_ss2"
	,"newMachine_subMachine1_ss3"
	,"newMachine_subMachine1_ss4"
};

#endif
