/**
	subMachine1.c

	This file automatically generated by FSMLang
*/

#include "subMachine1.h"




const SUB_MACHINE1_ACTION_TRANS subMachine1_action_array[subMachine1_numEvents][subMachine1_numStates] =
{
	{
		/* -- ee1 -- */

		/* -- ss1 -- */	{subMachine1_aa1,subMachine1_ss2}
		/* -- ss2 -- */	, {subMachine1_noAction, subMachine1_ss2}
		/* -- ss3 -- */	, {subMachine1_noAction, subMachine1_ss3}
		/* -- ss4 -- */	, {subMachine1_noAction, subMachine1_ss4}
	},
	{
		/* -- ee2 -- */

		/* -- ss1 -- */	{subMachine1_aa2,subMachine1_ss3}
		/* -- ss2 -- */	, {subMachine1_noAction, subMachine1_ss2}
		/* -- ss3 -- */	, {subMachine1_noAction, subMachine1_ss3}
		/* -- ss4 -- */	, {subMachine1_noAction, subMachine1_ss4}
	},
	{
		/* -- ee3 -- */

		/* -- ss1 -- */	{subMachine1_noAction, subMachine1_ss1}
		/* -- ss2 -- */	, {subMachine1_noAction, subMachine1_ss2}
		/* -- ss3 -- */	, {subMachine1_noAction, subMachine1_ss3}
		/* -- ss4 -- */	, {subMachine1_noAction, subMachine1_ss4}
	},
};
NEW_MACHINE_EVENT_ENUM subMachine1_sub_machine_fn(NEW_MACHINE_EVENT_ENUM e)
{
	return subMachine1FSM(psubMachine1, e);
}


NEW_MACHINE_SUB_FSM_IF subMachine1_sub_fsm_if =
{
		.subFSM = subMachine1_sub_machine_fn
	, .first_event = newMachine_subMachine1_ee1
	, .last_event = newMachine_subMachine1_ee3
};

SUB_MACHINE1 subMachine1 = {
	subMachine1_ss1,
	newMachine_subMachine1_ee1,
	&subMachine1_action_array,
	subMachine1FSM
};

pSUB_MACHINE1 psubMachine1 = &subMachine1;

static void runAppropriateEntryFunction(SUB_MACHINE1_STATE);
static void runAppropriateExitFunction(SUB_MACHINE1_STATE);
#ifndef EVENT_IS_NOT_EXCLUDED_FROM_LOG
#define EVENT_IS_NOT_EXCLUDED_FROM_LOG(e) (e == e)
#endif
NEW_MACHINE_EVENT_ENUM subMachine1FSM(pSUB_MACHINE1 pfsm, NEW_MACHINE_EVENT_ENUM event)
{
/* writeOriginalSubFSM */
	NEW_MACHINE_EVENT_ENUM new_e;

	NEW_MACHINE_EVENT_ENUM e = event;

	SUB_MACHINE1_STATE new_s;

	while (
		(e != THIS(noEvent))
		&& (e >= THIS(ee1))
	)
	{

#ifdef SUB_MACHINE1_DEBUG
if (EVENT_IS_NOT_EXCLUDED_FROM_LOG(e))
{
	DBG_PRINTF("event: %s; state: %s"
,SUB_MACHINE1_EVENT_NAMES[e - THIS(ee1)]
,SUB_MACHINE1_STATE_NAMES[pfsm->state]
);
}
#endif

	/* This is read-only data to facilitate error reporting in action functions */
	pfsm->event = e;

		new_e = ((* (*pfsm->actionArray)[e - THIS(ee1)][pfsm->state].action)(pfsm));

		new_s = (*pfsm->actionArray)[e - THIS(ee1)][pfsm->state].transition;


		if (pfsm->state != new_s)
		{
		runAppropriateExitFunction(pfsm->state);
		runAppropriateEntryFunction(new_s);
			pfsm->state = new_s;

		}

		e = new_e;

	} 
	return e == THIS(noEvent) ? PARENT(noEvent) : e;

}

static void runAppropriateEntryFunction(SUB_MACHINE1_STATE s)
{
	switch(s)
	{
	case subMachine1_ss1:
		subMachine1_foo();
		break;
	case subMachine1_ss2:
		subMachine1_onEntryTo_ss2();
		break;
	case subMachine1_ss3:
		subMachine1_foo1();
		break;
	default:
		break;
	}
}

static void runAppropriateExitFunction(SUB_MACHINE1_STATE s)
{
	switch(s)
	{
	case subMachine1_ss1:
		subMachine1_bar();
		break;
	case subMachine1_ss2:
		subMachine1_onExitFrom_ss2();
		break;
	case subMachine1_ss4:
		subMachine1_bar1();
		break;
	default:
		break;
	}
}

NEW_MACHINE_EVENT_ENUM __attribute__((weak)) subMachine1_aa1(pSUB_MACHINE1 pfsm)
{
	DBG_PRINTF("weak: subMachine1_aa1");
	return THIS(noEvent);
}

NEW_MACHINE_EVENT_ENUM __attribute__((weak)) subMachine1_aa2(pSUB_MACHINE1 pfsm)
{
	DBG_PRINTF("weak: subMachine1_aa2");
	return THIS(noEvent);
}

NEW_MACHINE_EVENT_ENUM __attribute__((weak)) subMachine1_noAction(pSUB_MACHINE1 pfsm)
{
	DBG_PRINTF("weak: subMachine1_noAction");
	return PARENT(noEvent);
}

void __attribute__((weak)) subMachine1_ee1_dt(pNEW_MACHINE pfsm)
{
	(void) pfsm;
	DBG_PRINTF("weak: subMachine1_ee1_dt");
}


void __attribute__((weak)) subMachine1_foo(void)
{
	DBG_PRINTF("weak: subMachine1_foo");
}

void __attribute__((weak)) subMachine1_bar(void)
{
	DBG_PRINTF("weak: subMachine1_bar");
}

void __attribute__((weak)) subMachine1_onEntryTo_ss2(void)
{
	DBG_PRINTF("weak: subMachine1_onEntryTo_ss2");
}

void __attribute__((weak)) subMachine1_onExitFrom_ss2(void)
{
	DBG_PRINTF("weak: subMachine1_onExitFrom_ss2");
}

void __attribute__((weak)) subMachine1_foo1(void)
{
	DBG_PRINTF("weak: subMachine1_foo1");
}

void __attribute__((weak)) subMachine1_bar1(void)
{
	DBG_PRINTF("weak: subMachine1_bar1");
}


#ifdef SUB_MACHINE1_DEBUG
char *SUB_MACHINE1_EVENT_NAMES[] = {
	 "subMachine1_ee1"
	, "subMachine1_ee2"
	, "subMachine1_ee3"
	, "subMachine1_noEvent"
	, "subMachine1_numEvents"
};

char *SUB_MACHINE1_STATE_NAMES[] = {
	 "subMachine1_ss1"
	,"subMachine1_ss2"
	,"subMachine1_ss3"
	,"subMachine1_ss4"
};

#endif
