/**
	subMachine2.c

	This file automatically generated by FSMLang
*/

#include "subMachine2_priv.h"
#include <stddef.h>


#ifndef DBG_PRINTF
#define DBG_PRINTF(...)
#endif

static NEW_MACHINE_EVENT_ENUM subMachine2FSM(pSUB_MACHINE2,NEW_MACHINE_EVENT_ENUM);

static void * const subMachine2_INSTANCES[newMachine_numInstances];
static const SUB_MACHINE2_ACTION_TRANS subMachine2_action_array[THIS(numEvents)][subMachine2_numStates] =
{
	{
		/* -- eee1 -- */

		/* -- sss1 -- */	{UFMN(aaa1),subMachine2_sss2}
		/* -- sss2 -- */	, {UFMN(noAction), subMachine2_sss2}
		/* -- sss3 -- */	, {UFMN(noAction), subMachine2_sss3}
	},
	{
		/* -- eee2 -- */

		/* -- sss1 -- */	{UFMN(aaa2),subMachine2_sss3}
		/* -- sss2 -- */	, {UFMN(noAction), subMachine2_sss2}
		/* -- sss3 -- */	, {UFMN(noAction), subMachine2_sss3}
	},
	{
		/* -- eee3 -- */

		/* -- sss1 -- */	{UFMN(noAction), subMachine2_sss1}
		/* -- sss2 -- */	, {UFMN(noAction), subMachine2_sss2}
		/* -- sss3 -- */	, {UFMN(noAction), subMachine2_sss3}
	},
};

NEW_MACHINE_EVENT_ENUM THIS(sub_machine_fn)(const void *pfsm, NEW_MACHINE_EVENT_ENUM e)
{
	return ((FSM_TYPE_PTR)pfsm)->fsm((FSM_TYPE_PTR)pfsm,e);
}

NEW_MACHINE_SUB_FSM_IF newMachine_subMachine2_sub_fsm_if =
{
	  .subFSM = THIS(sub_machine_fn)
	, .instanceArray = &subMachine2_INSTANCES
	, .first_event = THIS(firstEvent)
	, .last_event = THIS(noEvent)
};

static SUB_MACHINE2 subMachine2_INSTANCE0 = {
	.state = subMachine2_sss1
	, .event = THIS(eee1)
	, .actionArray = &subMachine2_action_array
	, .instance = 0
	, .fsm = subMachine2FSM
	};
static void * const subMachine2_INSTANCES[newMachine_numInstances] = {
	  &subMachine2_INSTANCE0
};
#ifndef EVENT_IS_NOT_EXCLUDED_FROM_LOG
#define EVENT_IS_NOT_EXCLUDED_FROM_LOG(e) (e == e)
#endif
static NEW_MACHINE_EVENT_ENUM subMachine2FSM(pSUB_MACHINE2 pfsm, NEW_MACHINE_EVENT_ENUM event)
{
	NEW_MACHINE_EVENT_ENUM new_e;
	NEW_MACHINE_EVENT_ENUM e = event;
	while (
		(e != THIS(noEvent))
		&& (e >= THIS(eee1))
	)
	{

#ifdef NEW_MACHINE_SUB_MACHINE2_DEBUG
if ((EVENT_IS_NOT_EXCLUDED_FROM_LOG(e))
    && (e >= THIS(firstEvent))
    && (e < THIS(noEvent))
   )
{
	DBG_PRINTF("event: %s; state: %s"
,SUB_MACHINE2_EVENT_NAMES[e - THIS(firstEvent)]
,SUB_MACHINE2_STATE_NAMES[pfsm->state]
);
}
#endif

	/* This is read-only data to facilitate error reporting in action functions */
	pfsm->event = e;

		new_e = ((* (*pfsm->actionArray)[e - THIS(eee1)][pfsm->state].action)(pfsm));

		pfsm->state = (*pfsm->actionArray)[e - THIS(eee1)][pfsm->state].transition;

		e = new_e;


	}

	return e == THIS(noEvent) ? PARENT(noEvent) : e;

}

ACTION_RETURN_TYPE __attribute__((weak)) UFMN(aaa1)(FSM_TYPE_PTR pfsm)
{
	DBG_PRINTF("weak: %s", __func__);
	(void) pfsm;
	return THIS(noEvent);
}

ACTION_RETURN_TYPE __attribute__((weak)) UFMN(aaa2)(FSM_TYPE_PTR pfsm)
{
	DBG_PRINTF("weak: %s", __func__);
	(void) pfsm;
	return THIS(noEvent);
}

ACTION_RETURN_TYPE __attribute__((weak)) UFMN(noAction)(FSM_TYPE_PTR pfsm)
{
	DBG_PRINTF("weak: %s", __func__);
	(void) pfsm;
	return THIS(noEvent);
}


#ifdef NEW_MACHINE_SUB_MACHINE2_DEBUG
char *SUB_MACHINE2_EVENT_NAMES[] = {
	 "newMachine_subMachine2_eee1"
	,"newMachine_subMachine2_eee2"
	,"newMachine_subMachine2_eee3"
	, "subMachine2_noEvent"
	, "subMachine2_numEvents"
};

char *SUB_MACHINE2_STATE_NAMES[] = {
	 "newMachine_subMachine2_sss1"
	,"newMachine_subMachine2_sss2"
	,"newMachine_subMachine2_sss3"
};

#endif
