/**
	subMachine1_priv.h

	This file automatically generated by FSMLang
*/

#ifndef _SUBMACHINE1_PRIV_H_
#define _SUBMACHINE1_PRIV_H_

#include "top_level_submach.h"
#include "top_level.h"

#ifdef NEW_MACHINE_SUB_MACHINE1_DEBUG
#include <stdio.h>
#include <stdlib.h>
#endif

/*
	sub-machine events are included in the top-level machine event enumeration.
	These macros set the appropriate names for events from THIS machine
	and those from the PARENT machine.

	They may be turned off as needed.
*/
#ifndef NO_CONVENIENCE_MACROS
#undef UFMN
#define UFMN(A) newMachine_subMachine1_##A
#undef THIS
#define THIS(A) newMachine_subMachine1_##A
#undef STATE
#define STATE(A) subMachine1_##A
#undef ACTION_RETURN_TYPE
#define ACTION_RETURN_TYPE NEW_MACHINE_EVENT_ENUM
#undef FSM_TYPE_PTR
#define FSM_TYPE_PTR pSUB_MACHINE1
#undef DECLARE_INSTANCE
#define DECLARE_INSTANCE(A) FSM_TYPE_PTR A = (FSM_TYPE_PTR) pfsm
#undef DECLARE_TR_FN_RET_VAR
#define DECLARE_TR_FN_RET_VAR(A, B) SUB_MACHINE1_STATE A = STATE(B)
#undef RETURN_STATE
#define RETURN_STATE(A, B) A = STATE(B)
#undef TR_FN_RETURN_TYPE
#define TR_FN_RETURN_TYPE SUB_MACHINE1_STATE
#undef PARENT
#define PARENT(A) newMachine_##A
#endif

#ifdef NEW_MACHINE_SUB_MACHINE1_DEBUG
extern char *SUB_MACHINE1_EVENT_NAMES[];
extern char *SUB_MACHINE1_STATE_NAMES[];
#endif

typedef enum {
	subMachine1_ss1
	, subMachine1_ss2
	, subMachine1_ss3
	, subMachine1_ss4
	, subMachine1_numStates
}  SUB_MACHINE1_STATE;

typedef struct _subMachine1_struct_ SUB_MACHINE1, *pSUB_MACHINE1;
extern pSUB_MACHINE1 psubMachine1;

typedef NEW_MACHINE_EVENT_ENUM (*SUB_MACHINE1_ACTION_FN)(pSUB_MACHINE1);

typedef NEW_MACHINE_EVENT_ENUM (*SUB_MACHINE1_FSM)(pSUB_MACHINE1,NEW_MACHINE_EVENT_ENUM);

typedef enum { newMachine_subMachine1_numEvents = 3} NEW_MACHINE_SUB_MACHINE1_EVENTS;
typedef struct _newMachine_subMachine1_action_trans_struct_ {
	SUB_MACHINE1_ACTION_FN	action;
	SUB_MACHINE1_STATE	transition;
} SUB_MACHINE1_ACTION_TRANS, *pSUB_MACHINE1_ACTION_TRANS;

struct _subMachine1_struct_ {
	unsigned                    instance;
	SUB_MACHINE1_STATE          state;
	NEW_MACHINE_EVENT_ENUM      event;
	SUB_MACHINE1_ACTION_TRANS   const	(*actionArray)[newMachine_subMachine1_numEvents][subMachine1_numStates];
	SUB_MACHINE1_FSM           fsm;
};

NEW_MACHINE_EVENT_ENUM newMachine_subMachine1_aa1(pSUB_MACHINE1);
NEW_MACHINE_EVENT_ENUM newMachine_subMachine1_aa2(pSUB_MACHINE1);
NEW_MACHINE_EVENT_ENUM newMachine_subMachine1_noAction(pSUB_MACHINE1);


void newMachine_subMachine1_foo(void);
void newMachine_subMachine1_bar(void);
void newMachine_subMachine1_onEntryTo_ss2(void);
void newMachine_subMachine1_onExitFrom_ss2(void);
void newMachine_subMachine1_foo1(void);
void newMachine_subMachine1_bar1(void);

void newMachine_subMachine1_ee1_dt(pSUB_MACHINE1_DATA,pSUB_MACHINE1_EE1_DATA);
void newMachine_subMachine1_translate_ee2_data(pSUB_MACHINE1_DATA,pSUB_MACHINE1_EE2_DATA);



#endif
