package io.github.fsmlang.generated.newmachine

/**
 * parser-test12.kt
 *
 * This file generated by FSMLang
 */

enum class newMachineState {
    s1,
    s2,
    s3,
    noState
}

enum class newMachineEvent {
    e1,
    e2,
    e3,
    e4,
    e5,
    noEvent
}

sealed interface newMachineEventData {
    object None : newMachineEventData
}

data class newMachineEventStruct(
    val event: newMachineEvent,
    val eventData: newMachineEventData = newMachineEventData.None
)

open class newMachineUserHooks {
    open fun machineTransitionFn(fsm: newMachine) { println("newMachine_machineTransitionFn") }
    open fun a1(fsm: newMachine): newMachineState {
        println("newMachine_a1")
        return newMachineState.noState
    }
    open fun a2(fsm: newMachine): newMachineState {
        println("newMachine_a2")
        return newMachineState.noState
    }
    open fun transitionFn1(fsm: newMachine): newMachineState {
        println("newMachine_transitionFn1")
        return newMachineState.noState
    }
}

class newMachine(val hooks: newMachineUserHooks = newMachineUserHooks()) {
    var state: newMachineState = newMachineState.s1
    var event: newMachineEvent = newMachineEvent.noEvent

    private fun translateEventData(eventStruct: newMachineEventStruct) {
        when (eventStruct.event) {
            else -> {}
        }
    }

    fun dispatch(eventStruct: newMachineEventStruct) {
        translateEventData(eventStruct)
        var currentEvent = eventStruct.event
        this.event = currentEvent
        while (currentEvent != newMachineEvent.noEvent) {
            val prevState = state
            when (state) {
                newMachineState.s1 -> when (currentEvent) {
                    newMachineEvent.e1 -> {
                        state = hooks.a1(this)
                        currentEvent = newMachineEvent.noEvent
                    }
                    newMachineEvent.e2 -> {
                        currentEvent = newMachineEvent.noEvent
                    }
                    newMachineEvent.e3 -> {
                        currentEvent = newMachineEvent.noEvent
                    }
                    newMachineEvent.e4 -> {
                        currentEvent = newMachineEvent.noEvent
                    }
                    else -> currentEvent = newMachineEvent.noEvent
                }
                newMachineState.s2 -> when (currentEvent) {
                    newMachineEvent.e1 -> {
                        state = hooks.a2(this)
                        currentEvent = newMachineEvent.noEvent
                    }
                    newMachineEvent.e2 -> {
                        currentEvent = newMachineEvent.noEvent
                    }
                    newMachineEvent.e3 -> {
                        currentEvent = newMachineEvent.noEvent
                    }
                    newMachineEvent.e4 -> {
                        currentEvent = newMachineEvent.noEvent
                    }
                    else -> currentEvent = newMachineEvent.noEvent
                }
                newMachineState.s3 -> when (currentEvent) {
                    newMachineEvent.e1 -> {
                        state = hooks.a2(this)
                        currentEvent = newMachineEvent.noEvent
                    }
                    newMachineEvent.e2 -> {
                        currentEvent = newMachineEvent.noEvent
                    }
                    newMachineEvent.e3 -> {
                        currentEvent = newMachineEvent.noEvent
                    }
                    newMachineEvent.e4 -> {
                        currentEvent = newMachineEvent.noEvent
                    }
                    else -> currentEvent = newMachineEvent.noEvent
                }
                else -> currentEvent = newMachineEvent.noEvent
            }
            this.event = currentEvent
        if (state != prevState) {
            when (prevState) {
            else -> {}
            }
        }
        if (state != prevState) {
            when (state) {
            else -> {}
            }
        }
            if (state != prevState) {
                hooks.machineTransitionFn(this)
            }
        }
    }
}
