package io.github.fsmlang.generated.full_test73

/**
 * test_fsm.kt
 *
 * This file generated by FSMLang
 */

enum class testState {
    s1,
    s2,
    s3,
    noState
}

enum class testEvent {
    e1,
    e2,
    e3,
    noEvent
}

sealed interface testEventData {
    object None : testEventData
}

data class testEventStruct(
    val event: testEvent,
    val eventData: testEventData = testEventData.None
)

open class testUserHooks {
    open fun transitioning(fsm: test) { println("test_transitioning") }
    open fun a1(fsm: test): testEvent {
        println("test_a1")
        return testEvent.noEvent
    }
    open fun a2(fsm: test): testEvent {
        println("test_a2")
        return testEvent.noEvent
    }
    open fun a3(fsm: test): testEvent {
        println("test_a3")
        return testEvent.noEvent
    }
    open fun decommission_s1(fsm: test) { println("test_decommission_s1") }
    open fun prep_s2(fsm: test) { println("test_prep_s2") }
}

class test(val hooks: testUserHooks = testUserHooks()) {
    var state: testState = testState.s1
    var event: testEvent = testEvent.noEvent

    private fun translateEventData(eventStruct: testEventStruct) {
        when (eventStruct.event) {
            else -> {}
        }
    }

    fun dispatch(eventStruct: testEventStruct) {
        translateEventData(eventStruct)
        var currentEvent = eventStruct.event
        this.event = currentEvent
        while (currentEvent != testEvent.noEvent) {
            val prevState = state
            when (state) {
                testState.s1 -> when (currentEvent) {
                    testEvent.e1 -> {
                        currentEvent = hooks.a1(this)
                    }
                    testEvent.e2 -> {
                        currentEvent = hooks.a2(this)
                    }
                    testEvent.e3 -> {
                        currentEvent = hooks.a3(this)
                        state = testState.s2
                    }
                    else -> currentEvent = testEvent.noEvent
                }
                testState.s2 -> when (currentEvent) {
                    testEvent.e1 -> {
                        currentEvent = hooks.a1(this)
                    }
                    testEvent.e2 -> {
                        currentEvent = hooks.a2(this)
                    }
                    testEvent.e3 -> {
                        currentEvent = testEvent.noEvent
                        state = testState.s3
                    }
                    else -> currentEvent = testEvent.noEvent
                }
                testState.s3 -> when (currentEvent) {
                    testEvent.e1 -> {
                        currentEvent = hooks.a1(this)
                    }
                    testEvent.e2 -> {
                        currentEvent = hooks.a2(this)
                    }
                    testEvent.e3 -> {
                        currentEvent = testEvent.noEvent
                        state = testState.s1
                    }
                    else -> currentEvent = testEvent.noEvent
                }
                else -> currentEvent = testEvent.noEvent
            }
            this.event = currentEvent
        if (state != prevState) {
            when (prevState) {
            testState.s1 -> hooks.decommission_s1(this)
            else -> {}
            }
        }
        if (state != prevState) {
            when (state) {
            testState.s2 -> hooks.prep_s2(this)
            else -> {}
            }
        }
            if (state != prevState) {
                hooks.transitioning(this)
            }
        }
    }
}
