package io.github.fsmlang.generated.test_fsm

/**
 * test_fsm.kt
 *
 * This file generated by FSMLang
 */

enum class test_fsmState {
    s1,
    s2,
    noState
}

enum class test_fsmEvent {
    e1,
    e2,
    e3,
    noEvent
}

sealed interface test_fsmEventData {
    object None : test_fsmEventData
    data class E1Payload(
        val i: Int = 0
    ) : test_fsmEventData
}

data class test_fsmEventStruct(
    val event: test_fsmEvent,
    val eventData: test_fsmEventData = test_fsmEventData.None
)

open class test_fsmUserHooks {
    open fun act_on_e1(fsm: test_fsm): test_fsmEvent {
        println("test_fsm_act_on_e1")
        return test_fsmEvent.noEvent
    }
    open fun act_on_e2(fsm: test_fsm): test_fsmEvent {
        println("test_fsm_act_on_e2")
        return test_fsmEvent.noEvent
    }
    open fun act_on_e3(fsm: test_fsm): test_fsmEvent {
        println("test_fsm_act_on_e3")
        return test_fsmEvent.noEvent
    }
    open fun guard1(fsm: test_fsm): test_fsmState {
        println("test_fsm_guard1")
        return test_fsmState.noState
    }
    open fun enter_s1(fsm: test_fsm) { println("test_fsm_enter_s1") }
    open fun leave_s2(fsm: test_fsm) { println("test_fsm_leave_s2") }
    open fun grab_e1_data(fsm: test_fsm, payload: test_fsmEventData.E1Payload): test_fsmEventData.E1Payload {
        println("test_fsm_grab_e1_data")
        return payload
    }
}

class test_fsm(val hooks: test_fsmUserHooks = test_fsmUserHooks()) {
    var state: test_fsmState = test_fsmState.s1
    var event: test_fsmEvent = test_fsmEvent.noEvent

    private fun translateEventData(eventStruct: test_fsmEventStruct) {
        when (eventStruct.event) {
            test_fsmEvent.e1 -> {
                val payload = eventStruct.eventData as? test_fsmEventData.E1Payload
                    ?: test_fsmEventData.E1Payload()
                hooks.grab_e1_data(this, payload)
            }
            else -> {}
        }
    }

    fun dispatch(eventStruct: test_fsmEventStruct) {
        translateEventData(eventStruct)
        var currentEvent = eventStruct.event
        this.event = currentEvent
        while (currentEvent != test_fsmEvent.noEvent) {
            val prevState = state
            when (state) {
                test_fsmState.s1 -> when (currentEvent) {
                    test_fsmEvent.e1 -> {
                        currentEvent = hooks.act_on_e1(this)
                    }
                    test_fsmEvent.e2 -> {
                        currentEvent = hooks.act_on_e2(this)
                        state = test_fsmState.s2
                    }
                    else -> currentEvent = test_fsmEvent.noEvent
                }
                test_fsmState.s2 -> when (currentEvent) {
                    test_fsmEvent.e1 -> {
                        currentEvent = hooks.act_on_e1(this)
                    }
                    test_fsmEvent.e3 -> {
                        currentEvent = hooks.act_on_e3(this)
                        state = hooks.guard1(this)
                    }
                    else -> currentEvent = test_fsmEvent.noEvent
                }
                else -> currentEvent = test_fsmEvent.noEvent
            }
            this.event = currentEvent
        if (state != prevState) {
            when (prevState) {
            test_fsmState.s2 -> hooks.leave_s2(this)
            else -> {}
            }
        }
        if (state != prevState) {
            when (state) {
            test_fsmState.s1 -> hooks.enter_s1(this)
            else -> {}
            }
        }
        }
    }
}
