package io.github.fsmlang.generated.top_level

/**
 * top_level.kt
 *
 * This file generated by FSMLang
 */

enum class top_levelState {
    s1,
    s2,
    s3,
    s4,
    noState
}

enum class top_levelEvent {
    e1,
    e2,
    e3,
    e4,
    e5,
    e6,
    e7,
    e8,
    noEvent
}

sealed interface top_levelEventData {
    object None : top_levelEventData
}

data class top_levelEventStruct(
    val event: top_levelEvent,
    val eventData: top_levelEventData = top_levelEventData.None
)

open class top_levelUserHooks {
    open fun a1(fsm: top_level): top_levelEvent {
        println("top_level_a1")
        return top_levelEvent.noEvent
    }
    open fun activate_sub_machine1(fsm: top_level): top_levelEvent {
        println("top_level_activate_sub_machine1")
        return top_levelEvent.noEvent
    }
    open fun activate_sub_machine2(fsm: top_level): top_levelEvent {
        println("top_level_activate_sub_machine2")
        return top_levelEvent.noEvent
    }
    open fun activate_sub_machine3(fsm: top_level): top_levelEvent {
        println("top_level_activate_sub_machine3")
        return top_levelEvent.noEvent
    }
    open fun handle_dispatch(fsm: top_level): top_levelEvent {
        println("top_level_handle_dispatch")
        return top_levelEvent.noEvent
    }
    open fun handle_other_passed_event(fsm: top_level): top_levelEvent {
        println("top_level_handle_other_passed_event")
        return top_levelEvent.noEvent
    }
}

class top_level(val hooks: top_levelUserHooks = top_levelUserHooks()) {
    var state: top_levelState = top_levelState.s1
    var event: top_levelEvent = top_levelEvent.noEvent

    private fun translateEventData(eventStruct: top_levelEventStruct) {
        when (eventStruct.event) {
            else -> {}
        }
    }

    fun dispatch(eventStruct: top_levelEventStruct) {
        translateEventData(eventStruct)
        var currentEvent = eventStruct.event
        this.event = currentEvent
        while (currentEvent != top_levelEvent.noEvent) {
            val prevState = state
            when (state) {
                top_levelState.s1 -> when (currentEvent) {
                    top_levelEvent.e1 -> {
                        currentEvent = hooks.a1(this)
                        state = top_levelState.s2
                    }
                    top_levelEvent.e6 -> {
                        currentEvent = hooks.handle_dispatch(this)
                    }
                    top_levelEvent.e7 -> {
                        currentEvent = hooks.handle_other_passed_event(this)
                    }
                    top_levelEvent.e8 -> {
                        currentEvent = top_levelEvent.noEvent
                        state = top_levelState.s4
                    }
                    else -> currentEvent = top_levelEvent.noEvent
                }
                top_levelState.s2 -> when (currentEvent) {
                    top_levelEvent.e2 -> {
                        currentEvent = hooks.activate_sub_machine1(this)
                    }
                    top_levelEvent.e3 -> {
                        currentEvent = hooks.activate_sub_machine2(this)
                    }
                    top_levelEvent.e4 -> {
                        currentEvent = hooks.activate_sub_machine3(this)
                        state = top_levelState.s3
                    }
                    top_levelEvent.e6 -> {
                        currentEvent = hooks.handle_dispatch(this)
                    }
                    top_levelEvent.e7 -> {
                        currentEvent = hooks.handle_other_passed_event(this)
                    }
                    top_levelEvent.e8 -> {
                        currentEvent = top_levelEvent.noEvent
                        state = top_levelState.s4
                    }
                    else -> currentEvent = top_levelEvent.noEvent
                }
                top_levelState.s3 -> when (currentEvent) {
                    top_levelEvent.e4 -> {
                        currentEvent = hooks.activate_sub_machine3(this)
                    }
                    top_levelEvent.e5 -> {
                        currentEvent = hooks.activate_sub_machine2(this)
                    }
                    top_levelEvent.e6 -> {
                        currentEvent = hooks.handle_dispatch(this)
                    }
                    top_levelEvent.e7 -> {
                        currentEvent = hooks.handle_other_passed_event(this)
                    }
                    top_levelEvent.e8 -> {
                        currentEvent = top_levelEvent.noEvent
                        state = top_levelState.s4
                    }
                    else -> currentEvent = top_levelEvent.noEvent
                }
                top_levelState.s4 -> when (currentEvent) {
                    top_levelEvent.e8 -> {
                        currentEvent = top_levelEvent.noEvent
                        state = top_levelState.s4
                    }
                    else -> currentEvent = top_levelEvent.noEvent
                }
                else -> currentEvent = top_levelEvent.noEvent
            }
            this.event = currentEvent
        if (state != prevState) {
            when (prevState) {
            else -> {}
            }
        }
        if (state != prevState) {
            when (state) {
            else -> {}
            }
        }
        }
    }
}
