##########################################
#
# makefile for individual test
#
#

override CFLAGS += -DTEST_FSM_DEBUG -I../
#override CFLAGS += -DFSM_DEBUG -DTEST_FSM_DEBUG -I../

include ../variants.mk


