"""
	matter.py

	This file generated by FSMLang

"""

from transitions import Machine

class Matter(object):



	def become_solid(self):
  		print("Entering solid state: I am now a solid block of ice.")

	def become_not_solid(self):
		print("Exiting solid state: I am no longer a solid.")

	def become_liquid(self):
		print("Entering liquid state: I am now a liquid puddle.")

	def become_not_liquid(self):
		print("Exiting liquid state: I am no longer a liquid.")

	def become_gaseous(self):
		print("Entering gas state: I am now a gas, vaporizing into the air.")

	def become_not_gaseous(self):
		print("Exiting gas state: I am no longer a gas.")


	states = [  {'name': 'solid', 'on_enter': ['become_solid'], 'on_exit': ['become_not_solid']}
	            , {'name': 'liquid', 'on_enter': ['become_liquid'], 'on_exit': ['become_not_liquid']}
	            , {'name': 'gas', 'on_enter': ['become_gaseous'], 'on_exit': ['become_not_gaseous']}
	          ]
	transitions = [
	               ['melt', 'solid', 'liquid']
	               , ['evaporate', 'liquid', 'gas']
	               , ['freeze', 'liquid', 'solid']
	               , ['condense', 'gas', 'liquid']
	               ]

	def __init__(self):
		self.machine = Machine(model=self, states=Matter.states, transitions=Matter.transitions, initial='solid')


