##########################################
#
# makefile for individual test
#
#

override CFLAGS += -DFSM_DEBUG -DNEW_MACHINE_DEBUG -I../
#override DIFF_FLAGS=-I \"Warning: Ignoring external event designations\"


include ../variants.mk
