override CFLAGS+=-DLEX_DEBUG

#here, it is only necessary to list source files that are not local to the current directory.
SRC=fsm_utils.c   \
    lexer_debug.c \
    ancestry.c \
    list.c

TARGET=diff_canonical

include ../unitTest.mk

