"""
	ns.py

	This file generated by FSMLang

"""

from transitions import Machine

class NarcolepticSuperhero(object):



	@property
	def choose_asleep(self):
		return True


	@property
	def choose_hanging_out(self):
		return False


	states = [	          'asleep'
	           ,'hanging_out'
	           ,'hungry'
	           ,'sweaty'
	           ,'saving_the_world'
	          ]
	transitions = [
	               {'trigger': 'distress_call'
	                 , 'source': ['asleep' ,'hanging_out' ,'hungry' ,'sweaty' ,'saving_the_world']
	                 , 'dest': 'saving_the_world'
	                 , 'before': 'change_into_super_secret_costume'
	                 }
	               , {'trigger': 'complete_mission'
	                 , 'source': 'saving_the_world'
	                 , 'dest': 'sweaty'
	                 , 'before': 'update_journal'
	                 }
	               , ['wake_up', 'asleep', 'hanging_out']
	               , ['work_out', 'hanging_out', 'hungry']
	               , ['eat', 'hungry', 'hanging_out']
	               , {'trigger': 'clean_up'
	                 , 'source': 'sweaty'
	                 , 'dest': 'asleep'
	                 , 'conditions': ['choose_asleep']
	                 }
	               , {'trigger': 'clean_up'
	                 , 'source': 'sweaty'
	                 , 'dest': 'hanging_out'
	                 , 'conditions': ['choose_hanging_out']
	                 }
	               ]

	def __init__(self):
		self.machine = Machine(model=self, states=NarcolepticSuperhero.states, transitions=NarcolepticSuperhero.transitions, initial='asleep')


	def change_into_super_secret_costume(self):
		print('change_into_super_secret_costume')


	def update_journal(self):
		print('update_journal')


	@property
	def choose_asleep(self):
		return True

	@property
	def choose_hanging_out(self):
		return True

