override CFLAGS+=-DLEX_DEBUG #-Dinit_list=stub_init_list

# Here, it is only necessary to list source files that are not local to the current directory.
SRC=util_file_inclusion.c

LIB_SRC=fsm_utils.c   \
        lexer_debug.c \
        list.c

include ../../unitTest.mk

