/**
	sub_machine3_priv.h

	This file automatically generated by FSMLang
*/

#ifndef _SUB_MACHINE3_PRIV_H_
#define _SUB_MACHINE3_PRIV_H_

#include "top_level_submach.h"
#include "top_level.h"

#ifdef TOP_LEVEL_SUB_MACHINE3_DEBUG
#include <stdio.h>
#include <stdlib.h>
#endif

/*
	sub-machine events are included in the top-level machine event enumeration.
	These macros set the appropriate names for events from THIS machine
	and those from the PARENT machine.

	They may be turned off as needed.
*/
#ifndef NO_CONVENIENCE_MACROS
#undef UFMN
#define UFMN(A) top_level_sub_machine3_##A
#undef THIS
#define THIS(A) top_level_sub_machine3_##A
#undef STATE
#define STATE(A) sub_machine3_##A
#undef ACTION_RETURN_TYPE
#define ACTION_RETURN_TYPE TOP_LEVEL_EVENT
#undef FSM_TYPE_PTR
#define FSM_TYPE_PTR pSUB_MACHINE3
#undef DECLARE_INSTANCE
#define DECLARE_INSTANCE(A) FSM_TYPE_PTR A = (FSM_TYPE_PTR) pfsm
#undef DECLARE_TR_FN_RET_VAR
#define DECLARE_TR_FN_RET_VAR(A, B) SUB_MACHINE3_STATE A = STATE(B)
#undef RETURN_STATE
#define RETURN_STATE(A, B) A = STATE(B)
#undef TR_FN_RETURN_TYPE
#define TR_FN_RETURN_TYPE SUB_MACHINE3_STATE
#undef PARENT
#define PARENT(A) top_level_##A
#endif

#ifdef TOP_LEVEL_SUB_MACHINE3_DEBUG
extern char *SUB_MACHINE3_EVENT_NAMES[];
extern char *SUB_MACHINE3_STATE_NAMES[];
#endif

typedef enum {
	sub_machine3_s1
	, sub_machine3_s2
	, sub_machine3_s3
	, sub_machine3_numStates
}  SUB_MACHINE3_STATE;

typedef struct _sub_machine3_struct_ SUB_MACHINE3, *pSUB_MACHINE3;
extern pSUB_MACHINE3 psub_machine3;

typedef TOP_LEVEL_EVENT (*SUB_MACHINE3_ACTION_FN)(pSUB_MACHINE3);

typedef TOP_LEVEL_EVENT (*SUB_MACHINE3_FSM)(pSUB_MACHINE3,TOP_LEVEL_EVENT);

typedef TOP_LEVEL_EVENT (*SUB_MACHINE3_STATE_FN)(pSUB_MACHINE3,TOP_LEVEL_EVENT);

static const SUB_MACHINE3_STATE_FN sub_machine3_state_fn_array[sub_machine3_numStates];

struct _sub_machine3_struct_ {
	unsigned                instance;
	SUB_MACHINE3_STATE            state;
	TOP_LEVEL_EVENT               event;
	SUB_MACHINE3_STATE_FN   const (*statesArray)[sub_machine3_numStates];
	SUB_MACHINE3_FSM              fsm;
};


TOP_LEVEL_EVENT top_level_sub_machine3_a1(pSUB_MACHINE3);
TOP_LEVEL_EVENT top_level_sub_machine3_a2(pSUB_MACHINE3);
TOP_LEVEL_EVENT top_level_sub_machine3_a3(pSUB_MACHINE3);


#endif
