/**
	top_level.h

	This file automatically generated by FSMLang
*/

#ifndef _TOP_LEVEL_H_
#define _TOP_LEVEL_H_

#include "top_level_events.h"
#ifndef TOP_LEVEL_NATIVE_PROLOG
#define TOP_LEVEL_NATIVE_PROLOG

#ifdef TOP_LEVEL_DEBUG
#include <stdio.h>
#define DBG_PRINTF(...) printf(__VA_ARGS__); printf("\n")
#endif

#endif
#define FSM_VERSION "2.4.alpha-2"

#ifndef NO_CONVENIENCE_MACROS
#undef UFMN
#define UFMN(A) top_level_##A
#undef THIS
#define THIS(A) top_level_##A
#undef STATE
#define STATE(A) top_level_##A
#undef TOP_LEVEL
#define TOP_LEVEL(A) top_level_##A
#undef SUB_MACHINE1
#define SUB_MACHINE1(A) top_level_sub_machine1_##A
#undef SUB_MACHINE2
#define SUB_MACHINE2(A) top_level_sub_machine2_##A
#undef SUB_MACHINE3
#define SUB_MACHINE3(A) top_level_sub_machine3_##A
#undef ACTION_RETURN_TYPE
#define ACTION_RETURN_TYPE TOP_LEVEL_EVENT
#undef DECLARE_TR_FN_RET_VAR
#define DECLARE_TR_FN_RET_VAR(A, B) TOP_LEVEL_STATE A = STATE(B)
#undef RETURN_STATE
#define RETURN_STATE(A, B) A = STATE(B)
#undef TR_FN_RETURN_TYPE
#define TR_FN_RETURN_TYPE TOP_LEVEL_STATE
#endif

typedef enum {
	  top_level_instance_0
	, top_level_numInstances
} TOP_LEVEL_INSTANCE;



void run_top_level(TOP_LEVEL_EVENT);

typedef struct _top_level_struct_ *pTOP_LEVEL;
extern pTOP_LEVEL ptop_level;


#endif
