/**
	top_level_submach.h

	This file automatically generated by FSMLang
*/

#ifndef _TOP_LEVEL_SUBMACH_H_
#define _TOP_LEVEL_SUBMACH_H_

#include "top_level.h"
#ifndef TOP_LEVEL_NATIVE_PROLOG
#define TOP_LEVEL_NATIVE_PROLOG

#ifdef TOP_LEVEL_DEBUG
#include <stdio.h>
#define DBG_PRINTF(...) printf(__VA_ARGS__); printf("\n")
#endif

#endif
/* Sub Machine Declarations */

typedef enum {
	 sub_machine1_e
	, top_level_firstSubMachine = sub_machine1_e
	,  sub_machine2_e
	,  sub_machine3_e
	, top_level_numSubMachines
} TOP_LEVEL_SUB_MACHINES;

typedef TOP_LEVEL_EVENT (*TOP_LEVEL_SUB_MACHINE_FN)(const void*,TOP_LEVEL_EVENT);
typedef struct _top_level_sub_fsm_if_ TOP_LEVEL_SUB_FSM_IF, *pTOP_LEVEL_SUB_FSM_IF;
struct _top_level_sub_fsm_if_
{
	TOP_LEVEL_EVENT           first_event;
	TOP_LEVEL_EVENT           last_event;
	TOP_LEVEL_SUB_MACHINE_FN   const subFSM;
	void * 	const              (*instanceArray)[top_level_numInstances];
};

extern TOP_LEVEL_SUB_FSM_IF top_level_sub_machine1_sub_fsm_if;
extern TOP_LEVEL_SUB_FSM_IF top_level_sub_machine2_sub_fsm_if;
extern TOP_LEVEL_SUB_FSM_IF top_level_sub_machine3_sub_fsm_if;

#endif
