/**
	top_level_priv.h

	This file automatically generated by FSMLang
*/

#ifndef _TOP_LEVEL_PRIV_H_
#define _TOP_LEVEL_PRIV_H_

#include "top_level.h"
#ifndef TOP_LEVEL_NATIVE_PROLOG
#define TOP_LEVEL_NATIVE_PROLOG

#ifdef TOP_LEVEL_DEBUG
#include <stdio.h>
#define DBG_PRINTF(...) printf(__VA_ARGS__); printf("\n")
#endif

#endif

#ifdef TOP_LEVEL_DEBUG
#include <stdio.h>
#include <stdlib.h>
#endif

#undef FSM_TYPE_PTR
#define FSM_TYPE_PTR pTOP_LEVEL
#undef DECLARE_INSTANCE
#define DECLARE_INSTANCE(A) FSM_TYPE_PTR A = (FSM_TYPE_PTR) pfsm

#ifdef TOP_LEVEL_DEBUG
extern char *TOP_LEVEL_EVENT_NAMES[];
extern char *TOP_LEVEL_STATE_NAMES[];
#endif

typedef enum {
	top_level_s1
	, top_level_s2
	, top_level_s3
	, top_level_numStates
}  TOP_LEVEL_STATE;

typedef struct _top_level_struct_ TOP_LEVEL;
typedef TOP_LEVEL_EVENT (*TOP_LEVEL_ACTION_FN)(pTOP_LEVEL);

typedef void (*TOP_LEVEL_FSM)(pTOP_LEVEL,TOP_LEVEL_EVENT);

void top_levelFSM(pTOP_LEVEL,TOP_LEVEL_EVENT);

#include "top_level_submach.h"
typedef TOP_LEVEL_EVENT (*TOP_LEVEL_STATE_FN)(pTOP_LEVEL,TOP_LEVEL_EVENT);

static const TOP_LEVEL_STATE_FN top_level_state_fn_array[top_level_numStates];

struct _top_level_struct_ {
	unsigned               instance;
	TOP_LEVEL_STATE              state;
	TOP_LEVEL_EVENT              event;
	TOP_LEVEL_STATE_FN     const (*statesArray)[top_level_numStates];
	pTOP_LEVEL_SUB_FSM_IF   const (*subMachineArray)[top_level_numSubMachines];
	TOP_LEVEL_FSM                fsm;
};


TOP_LEVEL_EVENT top_level_a1(pTOP_LEVEL);
TOP_LEVEL_EVENT top_level_activate_sub_machine1(pTOP_LEVEL);
TOP_LEVEL_EVENT top_level_activate_sub_machine2(pTOP_LEVEL);
TOP_LEVEL_EVENT top_level_activate_sub_machine3(pTOP_LEVEL);

void UFMN(foo)(pTOP_LEVEL,TOP_LEVEL_STATE);



#endif
