/**
	top_level_events.h

	This file automatically generated by FSMLang
*/

#ifndef _TOP_LEVEL_EVENTS_H_
#define _TOP_LEVEL_EVENTS_H_

#ifndef TOP_LEVEL_NATIVE_PROLOG
#define TOP_LEVEL_NATIVE_PROLOG

#ifdef TOP_LEVEL_DEBUG
#include <stdio.h>
#define DBG_PRINTF(...) printf(__VA_ARGS__); printf("\n")
#endif

#endif
typedef enum TOP_LEVEL_EVENT {
	 top_level_e1
	, top_level_e2
	, top_level_e3
	, top_level_e4
	, top_level_e5
	, top_level_noEvent
	, top_level_numEvents
	, top_level_sub_machine1_firstEvent
	, top_level_sub_machine1_e1 = top_level_sub_machine1_firstEvent
	, top_level_sub_machine1_e2
	, top_level_sub_machine1_e3
	, top_level_sub_machine1_noEvent
	, top_level_sub_machine2_firstEvent
	, top_level_sub_machine2_e1 = top_level_sub_machine2_firstEvent
	, top_level_sub_machine2_e2
	, top_level_sub_machine2_e3
	, top_level_sub_machine2_noEvent
	, top_level_sub_machine3_firstEvent
	, top_level_sub_machine3_e1 = top_level_sub_machine3_firstEvent
	, top_level_sub_machine3_e2
	, top_level_sub_machine3_e3
	, top_level_sub_machine3_noEvent
	, top_level_numAllEvents
}  TOP_LEVEL_EVENT;


#endif
