##########################################
#
# makefile for individual test
#
#

override CFLAGS += -DFSM_DEBUG -DTEST4_FSM_DEBUG -I../

FSM_SRC = parser-test4.fsm

SRC = pt4-actions.c


include ../test.mk
include ../../fsmrules.mk
