/**
	subMachine2.c

	This file automatically generated by FSMLang
*/

#include "subMachine2.h"




const SUB_MACHINE2_ACTION_TRANS subMachine2_action_array[subMachine2_numEvents][subMachine2_numStates] =
{
	{
		/* -- eee1 -- */

		/* -- sss1 -- */	{subMachine2_aaa1,subMachine2_sss2}
		/* -- sss2 -- */	, {subMachine2_noAction, subMachine2_sss2}
		/* -- sss3 -- */	, {subMachine2_noAction, subMachine2_sss3}
	},
	{
		/* -- eee2 -- */

		/* -- sss1 -- */	{subMachine2_aaa2,subMachine2_sss3}
		/* -- sss2 -- */	, {subMachine2_noAction, subMachine2_sss2}
		/* -- sss3 -- */	, {subMachine2_noAction, subMachine2_sss3}
	},
	{
		/* -- eee3 -- */

		/* -- sss1 -- */	{subMachine2_noAction, subMachine2_sss1}
		/* -- sss2 -- */	, {subMachine2_noAction, subMachine2_sss2}
		/* -- sss3 -- */	, {subMachine2_noAction, subMachine2_sss3}
	},
};
NEW_MACHINE_EVENT subMachine2_sub_machine_fn(NEW_MACHINE_EVENT e)
{
	return subMachine2FSM(psubMachine2, e);
}


NEW_MACHINE_SUB_FSM_IF subMachine2_sub_fsm_if =
{
		.subFSM = subMachine2_sub_machine_fn
	, .first_event = newMachine_subMachine2_eee1
	, .last_event = newMachine_subMachine2_eee3
};

SUB_MACHINE2 subMachine2 = {
	subMachine2_sss1,
	newMachine_subMachine2_eee1,
	&subMachine2_action_array,
	subMachine2FSM
};

pSUB_MACHINE2 psubMachine2 = &subMachine2;

#ifndef EVENT_IS_NOT_EXCLUDED_FROM_LOG
#define EVENT_IS_NOT_EXCLUDED_FROM_LOG(e) (e == e)
#endif
NEW_MACHINE_EVENT subMachine2FSM(pSUB_MACHINE2 pfsm, NEW_MACHINE_EVENT event)
{
/* writeOriginalSubFSM */
	NEW_MACHINE_EVENT new_e;

	NEW_MACHINE_EVENT e = event;

	while (
		(e != THIS(noEvent))
		&& (e >= THIS(eee1))
	)
	{

#ifdef SUB_MACHINE2_DEBUG
if (EVENT_IS_NOT_EXCLUDED_FROM_LOG(e))
{
	DBG_PRINTF("event: %s; state: %s"
,SUB_MACHINE2_EVENT_NAMES[e - THIS(eee1)]
,SUB_MACHINE2_STATE_NAMES[pfsm->state]
);
}
#endif

	/* This is read-only data to facilitate error reporting in action functions */
	pfsm->event = e;

		new_e = ((* (*pfsm->actionArray)[e - THIS(eee1)][pfsm->state].action)(pfsm));

		pfsm->state = (*pfsm->actionArray)[e - THIS(eee1)][pfsm->state].transition;

		e = new_e;

	} 
	return e == THIS(noEvent) ? PARENT(noEvent) : e;

}

NEW_MACHINE_EVENT __attribute__((weak)) subMachine2_aaa1(pSUB_MACHINE2 pfsm)
{
	DBG_PRINTF("weak: subMachine2_aaa1");
	(void) pfsm;
	return THIS(noEvent);
}

NEW_MACHINE_EVENT __attribute__((weak)) subMachine2_aaa2(pSUB_MACHINE2 pfsm)
{
	DBG_PRINTF("weak: subMachine2_aaa2");
	(void) pfsm;
	return THIS(noEvent);
}

NEW_MACHINE_EVENT __attribute__((weak)) subMachine2_noAction(pSUB_MACHINE2 pfsm)
{
	DBG_PRINTF("weak: subMachine2_noAction");
	(void) pfsm;
	return PARENT(noEvent);
}



#ifdef SUB_MACHINE2_DEBUG
char *SUB_MACHINE2_EVENT_NAMES[] = {
	 "subMachine2_eee1"
	, "subMachine2_eee2"
	, "subMachine2_eee3"
	, "subMachine2_noEvent"
	, "subMachine2_numEvents"
};

char *SUB_MACHINE2_STATE_NAMES[] = {
	 "subMachine2_sss1"
	,"subMachine2_sss2"
	,"subMachine2_sss3"
};

#endif
