/**
	subMachine1.c

	This file automatically generated by FSMLang
*/

#include "subMachine1.h"




const SUB_MACHINE1_ACTION_TRANS subMachine1_action_array[subMachine1_numEvents][subMachine1_numStates] =
{
	{
		/* -- ee1 -- */

		/* -- ss1 -- */	{subMachine1_aa1,subMachine1_ss2}
		/* -- ss2 -- */	, {subMachine1_noAction, subMachine1_ss2}
		/* -- ss3 -- */	, {subMachine1_noAction, subMachine1_ss3}
	},
	{
		/* -- ee2 -- */

		/* -- ss1 -- */	{subMachine1_aa2,subMachine1_ss3}
		/* -- ss2 -- */	, {subMachine1_noAction, subMachine1_ss2}
		/* -- ss3 -- */	, {subMachine1_noAction, subMachine1_ss3}
	},
	{
		/* -- ee3 -- */

		/* -- ss1 -- */	{subMachine1_noAction, subMachine1_ss1}
		/* -- ss2 -- */	, {subMachine1_noAction, subMachine1_ss2}
		/* -- ss3 -- */	, {subMachine1_noAction, subMachine1_ss3}
	},
};
NEW_MACHINE_EVENT subMachine1_sub_machine_fn(NEW_MACHINE_EVENT e)
{
	return subMachine1FSM(psubMachine1, e);
}


NEW_MACHINE_SUB_FSM_IF subMachine1_sub_fsm_if =
{
		.subFSM = subMachine1_sub_machine_fn
	, .first_event = newMachine_subMachine1_ee1
	, .last_event = newMachine_subMachine1_ee3
};


pSUB_MACHINE1_SUB_FSM_IF subMachine1_sub_fsm_if_array[subMachine1_numSubMachines] =
{
	&subSubMachine1_sub_fsm_if
};

SUB_MACHINE1 subMachine1 = {
	subMachine1_ss1,
	newMachine_subMachine1_ee1,
	&subMachine1_action_array,
	&subMachine1_sub_fsm_if_array,
	subMachine1FSM
};

pSUB_MACHINE1 psubMachine1 = &subMachine1;

#ifndef EVENT_IS_NOT_EXCLUDED_FROM_LOG
#define EVENT_IS_NOT_EXCLUDED_FROM_LOG(e) (e == e)
#endif
NEW_MACHINE_EVENT subMachine1FSM(pSUB_MACHINE1 pfsm, NEW_MACHINE_EVENT event)
{
/* writeOriginalSubFSM */
	NEW_MACHINE_EVENT new_e;

	NEW_MACHINE_EVENT e = event;

	while (
		(e != THIS(noEvent))
		&& (e >= THIS(ee1))
	)
	{

#ifdef SUB_MACHINE1_DEBUG
if (EVENT_IS_NOT_EXCLUDED_FROM_LOG(e))
{
	DBG_PRINTF("event: %s; state: %s"
,SUB_MACHINE1_EVENT_NAMES[e - THIS(ee1)]
,SUB_MACHINE1_STATE_NAMES[pfsm->state]
);
}
#endif

	/* This is read-only data to facilitate error reporting in action functions */
	pfsm->event = e;

		if (e < THIS(noEvent))
		{

			new_e = ((* (*pfsm->actionArray)[e - THIS(ee1)][pfsm->state].action)(pfsm));

			pfsm->state = (*pfsm->actionArray)[e - THIS(ee1)][pfsm->state].transition;

			e = new_e;

		} 
		else
		{
			new_e = ((* (*pfsm->subMachineArray)[pfsm->active_sub_machine]->subFSM)(e));

		}

	}
	return e == THIS(noEvent) ? PARENT(noEvent) : e;

}

NEW_MACHINE_EVENT __attribute__((weak)) subMachine1_aa1(pSUB_MACHINE1 pfsm)
{
	DBG_PRINTF("weak: subMachine1_aa1");
	(void) pfsm;
	return THIS(noEvent);
}

NEW_MACHINE_EVENT __attribute__((weak)) subMachine1_aa2(pSUB_MACHINE1 pfsm)
{
	DBG_PRINTF("weak: subMachine1_aa2");
	(void) pfsm;
	return THIS(noEvent);
}

NEW_MACHINE_EVENT __attribute__((weak)) subMachine1_noAction(pSUB_MACHINE1 pfsm)
{
	DBG_PRINTF("weak: subMachine1_noAction");
	(void) pfsm;
	return PARENT(noEvent);
}



#ifdef SUB_MACHINE1_DEBUG
char *SUB_MACHINE1_EVENT_NAMES[] = {
	 "subMachine1_ee1"
	, "subMachine1_ee2"
	, "subMachine1_ee3"
	, "subMachine1_noEvent"
	, "subMachine1_numEvents"
	, "subMachine1_subSubMachine1_y1"
	, "subMachine1_subSubMachine1_y2"
	, "subMachine1_subSubMachine1_noEvent"
};

char *SUB_MACHINE1_STATE_NAMES[] = {
	 "subMachine1_ss1"
	,"subMachine1_ss2"
	,"subMachine1_ss3"
};

#endif
