override CFLAGS+=-DLEX_DEBUG

#here, it is only necessary to list source files that are not local to the current directory.
SRC=fsm_utils.c    \
	 revision.c     \
	 list.c         \
	 ancestry.c     \
	 lexer_debug.c 

TARGET=diff_canonical

include ../unitTest.mk

