/**
	sub.h

	This file automatically generated by FSMLang
*/

#ifndef _SUB_H_
#define _SUB_H_

#include "sub_events.h"
#define FSM_VERSION "1.44"

#ifndef NO_CONVENIENCE_MACROS
#undef UFMN
#define UFMN(A) sub_##A
#undef THIS
#define THIS(A) sub_##A
#endif
#undef STATE
#define STATE(A) sub_##A

#undef ACTION_RETURN_TYPE
#define ACTION_RETURN_TYPE SUB_EVENT

void run_sub(SUB_EVENT);

typedef struct _sub_struct_ *pSUB;
extern pSUB psub;


#endif
