/**
	top_level_events.h

	This file automatically generated by FSMLang
*/

#ifndef _TOP_LEVEL_EVENTS_H_
#define _TOP_LEVEL_EVENTS_H_

#ifndef NEW_MACHINE_NATIVE_PROLOG
#define NEW_MACHINE_NATIVE_PROLOG

#include "test.h"
#define NUM_INTS (2)
#define NUM_CHARS (20)
#define INIT_FSM_DATA {.u.bop = {[0 ... (NUM_CHARS - 1)] = '\0'}  \
                       , .u.foo.a = {[0 ... (NUM_INTS - 1)] = 0}  \
                       , .u.foo.count_ints = 0                    \
                       , .u.beep.f = 0                            \
                       }

#endif
/*
	Event Cross Reference:

	    0  newMachine_e1
	    1  newMachine_e2
	    2  newMachine_e3
	    3  newMachine_e4
	    4  newMachine_eShared
	    5  newMachine_noEvent
	    6  newMachine_numEvents
	    7  newMachine_subMachine1_eShared
	    8  newMachine_subMachine1_ee2
	    9  newMachine_subMachine1_ee3
	   10  newMachine_subMachine1_noEvent
	   11  newMachine_subMachine2_eee1
	   12  newMachine_subMachine2_eee2
	   13  newMachine_subMachine2_eee3
	   14  newMachine_subMachine2_noEvent
	   15  newMachine_numAllEvents

*/
typedef enum NEW_MACHINE_EVENT_ENUM {
	 newMachine_e1
	, newMachine_e2
	, newMachine_e3
	, newMachine_e4
	, newMachine_eShared
	, newMachine_noEvent
	, newMachine_numEvents
	, newMachine_subMachine1_firstEvent
	, newMachine_subMachine1_eShared = newMachine_subMachine1_firstEvent
	, newMachine_subMachine1_ee2
	, newMachine_subMachine1_ee3
	, newMachine_subMachine1_noEvent
	, newMachine_subMachine2_firstEvent
	, newMachine_subMachine2_eee1 = newMachine_subMachine2_firstEvent
	, newMachine_subMachine2_eee2
	, newMachine_subMachine2_eee3
	, newMachine_subMachine2_noEvent
	, newMachine_numAllEvents
}  NEW_MACHINE_EVENT_ENUM;


#endif
