##########################################
#
# makefile for individual test
#
#

override CFLAGS +=                                   \
			-DCOMPACT_DEBUG                             \
			-DCOMPACT_SUB_COMPACT_DEBUG                 \
			-DCOMPACT_SUB_COMPACT_SUB_SUB_COMPACT_DEBUG \
         -I../                                       \
	 		-Wall                                       \
	 		-ggdb


VARIANTS=cc

include ../variants.mk


